POST localhost:8080/rest/konsultation
Content-Type: application/json

{"cpr": "1110109996", "dato": "11.11", "tid": "1234", "konsultationstype": "test", "konsultationsvarighed":"1 time", "notat": "test2"}

###
GET localhost:8080/rest/konsultation/0212952438
